### ISSUE TITLE
Add capability to supply headers to RequestSpecification (including authorization headers)

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#11]
Hey,

Thanks again for this great package. Here are few things i would request to add to request Specification.

- HttpHeaders ( like Authorization and other basic headers doesn't need to be repeated )

**Comment by basdijkstra** [comment]
Thank you @bheemreddy181, those all make sense. I’ll split this into separate issues (one for each property) later this morning, if that’s OK with you. I like my issues and changes small and many, makes it easier to separate discussion and release.

**Comment by bheemreddy181** [comment]
Sounds good to me

**Comment by bheemreddy181** [comment]
Do you think we will have an ability to specify headers at request spec level and append any additional headers which are provided at the actual test ?

**Comment by basdijkstra** [comment]
> Do you think we will have an ability to specify headers at request spec level and append any additional headers which are provided at the actual test ?

Yes, absolutely.

**Comment by bheemreddy181** [comment]
Sounds good thanks

**Comment by bheemreddy181** [comment]
Really looking forward into this addition

**Comment by basdijkstra** [comment]
> Really looking forward into this addition

So do I, just need to find some time to work on this properly. Hopefully later this week so I can release 1.1.0 with all the additions around the weekend.

**Comment by basdijkstra** [comment]
@bheemreddy181 in the meantime, would you like to take a look at this one? See #23.

**Comment by basdijkstra** [comment]
Added this in #23, so closing. Created separate issue for the support for the Content-Type header.
