### ISSUE TITLE
Adapt .MultiPart to support enhanced file upload

### ISSUE THREAD

**Issue by RipaBogdan** [basdijkstra/rest-assured-net#110]
Can .MultiPart be addapted in order to allow dictionaries as input? 

There are situations where you need to upload a file and some additional details are required. 

Current implementation: 
MultiPart(FileInfo fileName, string controlName="file")

Would maybe require to accept a dictionary of type <string, object>, eg: 

```csharp
multiPart = new Dictionary<string, object>
 {
     {"projectId", "id"},
     { "type", "Model"}
     { "file", fileName }
 };
```

**Comment by basdijkstra** [comment]
Hey @RipaBogdan, sure, I'm happy to see if I can support that. To make it a little easier for me to implement, do you maybe have an example of what the final request should look like? Ideally sourced from a tool like Fiddler or WireShark.

Once I know that I'll think of a syntax that would support it, show that to you and if you're happy with it I'm happy to build in support for it.

**Comment by RipaBogdan** [comment]
Hi @basdijkstra, unfortunately I don't use these tools, however I can provide this as an example of what I'm talking about: 
![image](https://github.com/basdijkstra/rest-assured-net/assets/126170618/83949bc2-3839-4136-b180-9f4c0c7f110b)
The idea is to have the file as part of some dictionary structure. 
Maybe .FormData should instead be the one to be enhanced?

**Comment by basdijkstra** [comment]
Thanks for that. I'll see if I can find some more information on this.

By the way, it looks like this request is generated when some kind of web form is submitted. You wouldn't by any chance have a public example of such a form available for me to use / test, would you?

**Comment by basdijkstra** [comment]
@RipaBogdan do you have an example of such a form for me? Without a way to see what the request should look like it's going to be a little hard to implement this as I can't write tests for it.

**Comment by RipaBogdan** [comment]
unfortunately the form data above is all I have as an example, but the idea remains the same, we need a way to upload a file along with other fields.

**Comment by basdijkstra** [comment]
Got it. I’ll do some more research and will try to provide you with a test version soon.

**Comment by basdijkstra** [comment]
I think I'm getting somewhere here, but it does require me to rewrite some of the internals of how a request body is created.

It would be an improvement, though, so I'm happy to do it, but it might take me a bit more time. Will keep you posted, @RipaBogdan.

**Comment by basdijkstra** [comment]
@RipaBogdan can you tell me if there is a wrapper around the various elements in the screenshot you attached in https://github.com/basdijkstra/rest-assured-net/issues/110#issuecomment-1790824728 ?

This is what I've got now:
![image](https://github.com/basdijkstra/rest-assured-net/assets/10740451/839ec2e1-6376-47a1-838c-4fbb3d3b0377)
As you can see, there's an outer boundary `327d46c5-c7d6-481a-bf38-c7dff4a8f6ab` containing (right now) one nested element with the inner boundary `0b12acc5-347d-4b2f-98bf-fb0af5d696e1`.

I could probably very easily allow for more inner sections to be added here, and I _think_ this is the way to do it as a `HttpMessage` only has a singular `Content` property of type `HttpContent`, no `IEnumerable`, so it has to be any of these:

[System.Net.Http.ByteArrayContent](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.bytearraycontent?view=net-7.0)
[System.Net.Http.Json.JsonContent](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.json.jsoncontent?view=net-7.0)
[System.Net.Http.MultipartContent](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.multipartcontent?view=net-7.0)
[System.Net.Http.ReadOnlyMemoryContent](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.readonlymemorycontent?view=net-7.0)
[System.Net.Http.StreamContent](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.streamcontent?view=net-7.0)

And the `MultiPartContent` can have multiple segments like in your example.

So, again, is there are wrapper around the payload sections you showed in that screenshot? Can I see the entire payload?

**Comment by basdijkstra** [comment]
Note to self: I think this is the way to do it: https://brokul.dev/sending-files-and-additional-data-using-httpclient-in-net-core. Let me try and implement this over the weekend.

**Comment by basdijkstra** [comment]
Got it:
![image](https://github.com/basdijkstra/rest-assured-net/assets/10740451/88769e2e-eca5-4860-bde9-e7003477aca4)

Now all I need to do is think about what the methods should look like.

Right now, I simply added a method `MultiPart(HttpContent content, string name)` , but if you have to send many different fields, that might get ugly. It works, though, so this option will definitely be in there.

**Comment by basdijkstra** [comment]
Well, that was easier than expected.

```csharp
[Test]
public void AdditionalFieldsCanBeUploadedWithAFileUsingADictionary()
{
    Dictionary<string, HttpContent> additionalMultipartPayload = new Dictionary<string, HttpContent>()
    {
        { "projectId", new StringContent("PROJECT-1234") },
        { "projectName", new StringContent("MyProject") },
    };

    Given()
        .MultiPart(new FileInfo(this.csvFileName))
        .MultiPart(additionalMultipartPayload)
    .When()
        .Post($"{MOCK_SERVER_BASE_URL}/csv-multipart-form-data-additional-fields")
    .Then()
        .StatusCode(201);
}
```

`MultiPart()` now also accepts an argument of type `Dictionary<string, HttpContent>`. That means you can add as many fields as you want with a single call.

You can even add the file itself through the Dictionary, too, but you'll need to convert it to an object of type `HttpContent` yourself. That's not too difficult, though, you can do that like this:

Dictionary<string, HttpContent> multipartPayloadIncludingFile = new Dictionary<string, HttpContent>()
{
    { "file", new StreamContent(fileInfo.OpenRead()) },
    { "projectId", new StringContent("PROJECT-1234") },
    { "projectName", new StringContent("MyProject") },
};

where fileInfo is the `FileInfo` object used before.

@RipaBogdan what do you think? I've just published a new beta version so you can try it out for yourself, it's `4.2.0-beta.3`.

Please let me know what you think once you've tested it so I can release a proper 4.2.0 version soon (I've been planning to do this for a while).

**Comment by RipaBogdan** [comment]
@basdijkstra I have tested .MultiPart and can confirm that this solution is working as expected. 
Thank you!

**Comment by basdijkstra** [comment]
Awesome, thank you @RipaBogdan for your support. I'll release version 4.2.0 later this week, I want to do some final testing tomorrow (around .NET 8 support, not this feature).

Please note that I did change the order of arguments for one of the `MultiPart()` methods, from `Multipart(HttpContent content, string name)` to `MultiPart(string name, HttpContent content)` so it matches the order that the dictionary argument takes.

**Comment by RipaBogdan** [comment]
Hi @basdijkstra, there is a small thing that is giving us trouble regarding this .MultiPart file upload, that maybe can be something quick from your side. 
As you know, endpoints use various names for multipart/formdata fields, and it seems that .MultiPart automatically adds the name="file" to the field we use for uploading something. 
![image](https://github.com/basdijkstra/rest-assured-net/assets/126170618/1a070a50-5913-43da-908c-b86b4cece3ef)

I suspect this is causing our issues, since our endpoint looks for name="content". 
Is it possible to maybe add the "name" to be filled in by the user?

Thank you, 
Bogdan

**Comment by basdijkstra** [comment]
Hey @RipaBogdan, the old way of specifying a multipart file upload with the option to specify a custom control name is still available, would that work for you in this case?

See https://github.com/basdijkstra/rest-assured-net/blob/8f723d48e47db137bc5a884769034929e544c64f/RestAssured.Net.Tests/MultiPartFormDataTests.cs#L80

**Comment by RipaBogdan** [comment]
Unfortunately, it seems that we need a mix between the two, 
So something like this maybe, if it is possible:

`[Test]
public void AdditionalFieldsCanBeUploadedWithAFileUsingADictionary()
{
    Dictionary<string, HttpContent> additionalMultipartPayload = new Dictionary<string, HttpContent>()
    {
        { "projectId", new StringContent("PROJECT-1234") },
        { "projectName", new StringContent("MyProject") },
    };

    Given()
        **.MultiPart("Content", new FileInfo(this.csvFileName))**
        .MultiPart(additionalMultipartPayload)
    .When()
        .Post($"{MOCK_SERVER_BASE_URL}/csv-multipart-form-data-additional-fields")
    .Then()
        .StatusCode(201);
}`

**Comment by basdijkstra** [comment]
Have you tried doing just that? Because the way it’s implemented each additional call to `MultiPart` adds another section to the multipart content: https://github.com/basdijkstra/rest-assured-net/blob/8f723d48e47db137bc5a884769034929e544c64f/RestAssured.Net/Request/ExecutableRequest.cs#L295

I even have a test for it myself: https://github.com/basdijkstra/rest-assured-net/blob/8f723d48e47db137bc5a884769034929e544c64f/RestAssured.Net.Tests/MultiPartFormDataTests.cs#L140

If it doesn’t work as you expected my tests aren’t doing what they should :)

**Comment by RipaBogdan** [comment]
Indeed, it works, just needed to switch the parameters around: 

`.MultiPart(new FileInfo(csvFileName), "content")`

Thank you!

**Comment by basdijkstra** [comment]
No problem, you’re welcome!
