### ISSUE TITLE
Make `HttpCompletionOption` configurable

### ISSUE THREAD

**Issue by basdijkstra** [basdijkstra/rest-assured-net#126]
See this discussion for more details: https://github.com/basdijkstra/rest-assured-net/discussions/125

**Comment by basdijkstra** [comment]
@RothAndrew tagging you so you can follow the progress in here.

**Comment by basdijkstra** [comment]
@RothAndrew could you upgrade to https://www.nuget.org/packages/RestAssured.Net/4.3.0-beta.1 and test whether setting the `HttpCompletionOption` works as intended for you? Example:

```csharp
Given()
    .UseHttpCompletionOption(HttpCompletionOption.ResponseHeadersRead)
```

The value defaults to `HttpCompletionOption.ResponseContentRead`, so if that's the value you need, you don't have to change anything.

In this release, you can only set the `HttpCompletionOption` value for individual requests, not yet in the `RequestSpecification` or global config. I'll add that as soon as I know this is what you were looking for.

**Comment by RothAndrew** [comment]
Yep! Will give it a show now.

**Comment by RothAndrew** [comment]
It's working great! Thanks! 😁

**Comment by RothAndrew** [comment]
> If you can think of a better name for the UseHttpCompletionOption method I'm open to suggestions ;)

I've always been a fan of using descriptive names over short and cryptic so I love it.

I suppose if you really wanted something different I could potentially see the argument being

```
// Wait for all the content. Equivalent to using HttpCompletionOption.ResponseContentRead
Given()
  .WaitForContent(true)
  
// Don't wait for content. Equivalent to using HttpCompletionOption.ResponseHeadersRead
Given()
  .WaitForContent(false)
```

with the default being `true` to preserve backward compatibility

**Comment by basdijkstra** [comment]
Thanks so much for the feedback! Happy to hear it works. I’ll add the options to the `RequestSpecification` and the config options and will release a proper `4.3.0` soon.

**Comment by basdijkstra** [comment]
@RothAndrew RestAssured.Net 4.3.0 is live: https://www.nuget.org/packages/RestAssured.Net/4.3.0

You can now also specify the `HttpCompletionOption` in a `RequestSpecification` and in the global config. Feel free to install and test it.

Please let me know if all still works OK, so I can close the issue. Cheers!

**Comment by basdijkstra** [comment]
Any more feedback, @RothAndrew? If not I’ll close this issue.

**Comment by RothAndrew** [comment]
Nope, everything's great. thanks!
