### ISSUE TITLE
NTLM Authentication

### ISSUE THREAD

**Issue by basdijkstra** [basdijkstra/rest-assured-net#130]
### Discussed in https://github.com/basdijkstra/rest-assured-net/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **espy19** October 17, 2024</sup>
Hello. Just like `BasicAuth()` and `OAuth2()`, can we have something like `Ntlm()` so that the HTTP request uses the credentials of the current user? I can achieve this currently by passing my own `HttpClient` object (created using `Credentials = CredentialCache.DefaultNetworkCredentials`) but the `Ntlm()` wrapper could make it even easier.</div>

**Comment by basdijkstra** [comment]
Hey @espy19, I've added NTLM support as discussed. I don't exactly know how to properly test this, but debugging shows that the specified credentials are added to the `HttpClientHandler` as expected.

Could you please upgrade to `4.4.0-beta.1` and test this for me to see if it works as expected? If it does, I'll do a proper `4.4.0` release soon.

**Comment by espy19** [comment]
Tested the beta and both `Ntlm()` methods work as expected. Many thanks for the superfast turnaround time!

**Comment by basdijkstra** [comment]
Excellent, thank you for the quick feedback!

I’ll release a proper `4.4.0` version later today and will update CHANGELOG and docs accordingly.

**Comment by basdijkstra** [comment]
Version 4.4.0 is released. I renamed `Ntlm()` to `NtlmAuth()` to stay consistent with the other authentication methods, other than that there are no changes.

Thanks again @espy19 for reporting this. If you think this isn't working as it's supposed to after all, or if you have another question or request, feel free to open another issue.
