### ISSUE TITLE
Add capability to specify proxy to use in requests

### ISSUE THREAD

**Issue by basdijkstra** [basdijkstra/rest-assured-net#14]
The `HttpClient` we use under the hood has the capability to add a proxy. It could be useful to allow us to specify this as part of our test.

Should be supported both for individual requests as well as in a `RequestSpecification`.

Requested / suggested by @bheemreddy181.

**Comment by basdijkstra** [comment]
Merged in #18. @bheemreddy181, how does this look?

**Comment by bheemreddy181** [comment]
You are referring to this one https://github.com/basdijkstra/rest-assured-net/pull/20 I assume ?

**Comment by basdijkstra** [comment]
> You are referring to this one #20 I assume ?

Yes, apologies for the confusion!

**Comment by bheemreddy181** [comment]
Looks good to me

**Comment by basdijkstra** [comment]
Thanks, closing this one then.
