### ISSUE TITLE
Add capability to set custom timeout for requests

### ISSUE THREAD

**Issue by basdijkstra** [basdijkstra/rest-assured-net#15]
The default value for the `HttpClient` timeout is 100,000 milliseconds (100 seconds).

It would be useful to be able to set this to a different value, both for an individual request as well as through a `RequestSpecification`.

Requested / suggested by @bheemreddy181.

**Comment by basdijkstra** [comment]
Added support for custom timeouts to be set in individual tests. To be done: setting this as part of the `RequestSpecification`.

**Comment by basdijkstra** [comment]
Completed in #17.

**Comment by basdijkstra** [comment]
@bheemreddy181, feel free to have a look at this feature and give me some feedback :)

**Comment by bheemreddy181** [comment]
cool looks good to me. Thanks for adding this.
