### ISSUE TITLE
Add capability to set User-Agent for requests

### ISSUE THREAD

**Issue by basdijkstra** [basdijkstra/rest-assured-net#16]
We should be able to set the User-Agent for requests, both for individual requests as well as through a `RequestSpecification`.

Requested / suggested by @bheemreddy181.

**Comment by basdijkstra** [comment]
Merged into main in #18.

See https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#user-agent for documentation.

@bheemreddy181, another one you might want to have a look at.

**Comment by bheemreddy181** [comment]
Looks good to me, thanks for adding this

**Comment by basdijkstra** [comment]
Thanks for the suggestion!
