### ISSUE TITLE
[Suggestion] Rename Hostname to BaseUrl

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#19]
I feel the hostname is a bit confusing for any new users for this, do you think we can rename this to BaseUrl ?

**Comment by basdijkstra** [comment]
That's for the RequestSpecification, right? Let me think about that. I just copied the names from the properties you set on the `System.Uri` object. Also, a host name is slightly different from a base URL, a base URL is scheme + host name.

You set the scheme and the host name separately on a `System.Uri` object. I could add a utility method that sets both and call it `BaseUrl()` but I'm afraid that might make things more confusing, not less...

**Comment by bheemreddy181** [comment]
Or just that could be just BaseHost, than Hostname ?

**Comment by basdijkstra** [comment]
I’ve never heard that name being used, so I’d rather stick with HostName for now. I think that describes best what should be passed as an argument value. I’ll think about adding a BaseUrl method that aceepts {Scheme}://{HostName} as a value, but that’ll have to come with additional parsing and exception handling..

**Comment by bheemreddy181** [comment]
Sounds good to me as I kept thinking the existing name sound good to me

**Comment by basdijkstra** [comment]
OK, let's keep it as is. I appreciate your ideas, though, so keep them coming.
