### ISSUE TITLE
Add utility methods for Content-Type header in RequestSpecification

### ISSUE THREAD

**Issue by basdijkstra** [basdijkstra/rest-assured-net#24]
We should be able to set the `Content-Type` header through a RequestSpecification as well.

**Comment by basdijkstra** [comment]
Added this just now, also updated documentation. See this test:

https://github.com/basdijkstra/rest-assured-net/blob/f12c689c745209ad477acb377ece76a416c2bd12/RestAssured.Net.Tests/RequestSpecificationTests.cs#L121

**Comment by bheemreddy181** [comment]
Thanks for adding this - when can I expect the new release to go out ?

**Comment by basdijkstra** [comment]
Depending on how quickly I can fix those two issues am that are still open, hopefully over the weekend.

**Comment by basdijkstra** [comment]
@bheemreddy181 that went a little quicker than expected, version 1.1.1 is live with all the changes. Thanks again for all the support so far.
