### ISSUE TITLE
Ability to Configure load test with the number of threads and amount of time in seconds to run the test with

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#27]
Do you think providing an ability to load test the api is a good use case for this ?

**Comment by basdijkstra** [comment]
I’ll keep it in mind but that’s an entirely different use case. It would probably take a major rework of the way I built the code.

I’d rather focus on getting the ‘functional’ stuff right first.

**Comment by bheemreddy181** [comment]
Sounds good to me thanks. Thanks for patiently listening to my ideas here :)

**Comment by bheemreddy181** [comment]
I can close this for time being. This is not a high priority for me at this point but thought a good use case to have.

**Comment by basdijkstra** [comment]
No I'm happy to leave this open, that's why I added the 'maybe-some-day' label.

**Comment by basdijkstra** [comment]
Looking back at this issue I'm going to close it now, @bheemreddy181, as I don't think this is something I'll implement soon.
