### ISSUE TITLE
[Suggestion] Ability to retry on a specific type of error 

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#28]
Hey,

Do you think we can give an ability to retry the API based on a specific error ? I think we can handle this outside of the package like in the CICD pipeline, but having an ability to retry will be good I feel. What do you think ?

**Comment by basdijkstra** [comment]
Hey @bheemreddy, short answer: no. I think retrying tests is a very bad practice, and it's not something I want to stimulate by enabling it in RestAssured .Net. If people really want to retry their tests, that's their choice, and they can use something like this: https://docs.nunit.org/articles/nunit/writing-tests/attributes/retry.html, but it's bad behaviour that should not be encouraged.

Here's a longer rant on this I wrote a while ago: https://www.ontestautomation.com/stop-sweeping-your-failing-tests-under-the-rug/

So, closing this as 'won't fix'.

**Comment by bheemreddy181** [comment]
Sounds good to me I completely agree with you retrying is really a bad feature and I am not a big fan too. 

My use case was post deployment an azure app service takes almost a min or two come back up so api tests fail in the initial couple runs but I guess I should handle this In a different way and make sure I am not retrying my tests.
