### ISSUE TITLE
SSL error for creating token using FormData 

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#29]
Hey @basdijkstra ,

Newer version is throwing errors while creating a token using FormData

<img width="1223" alt="Screen Shot 2022-11-12 at 4 44 24 PM" src="https://user-images.githubusercontent.com/101338506/201497873-c95dbab8-4c58-463b-b0cd-ee3bb120b110.png">

**Comment by basdijkstra** [comment]
Hey @bheemreddy181, can you please include a test with your bug reports that I can use to reproduce this behaviour? Without that it's impossible to see what happens here.

**Comment by basdijkstra** [comment]
Also, what happens when you disable SSL checks using `RelaxedHttpsValidation()` ?

https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#disabling-ssl-checks

**Comment by bheemreddy181** [comment]
Ok I will create a test and share it with you. It might take some more time to get back. Thanks

**Comment by bheemreddy181** [comment]
> Hey @bheemreddy181, can you please include a test with your bug reports that I can use to reproduce this behaviour? Without that it's impossible to see what happens here.

The OuAth2 token generation data is pretty private, I am not in a position to share the example at this point. But it works with  .RelaxedHttpsValidation() added.

**Comment by basdijkstra** [comment]
OK, that’s what I expected. Is that enough of an answer for you right now?

**Comment by bheemreddy181** [comment]
I am surprised from what changed from before to now are we always expected to set RelaxedHttpsValidation() all the time ?

**Comment by basdijkstra** [comment]
Well what changed is that with RelaxedHttpsValidation() you essentially told the HttpClient to allow untrusted certificates. I got the idea from here: https://stackoverflow.com/questions/12553277/allowing-untrusted-ssl-certificates-with-httpclient

The original REST Assured in Java does much the same thing by the way: https://github.com/rest-assured/rest-assured/wiki/Usage#ssl

I’m not saying you should use this setting all the time, but it’s one way to deal with SSL. If this isn’t OK for you or you want more fine grained control, can I please ask you to open another issue with your specific requirements?

**Comment by bheemreddy181** [comment]
Sure I can create one. This worked before without setting ssl setup.
