### ISSUE TITLE
WireMock.Net.FluentAssertions?

### ISSUE THREAD

**Issue by StefH** [basdijkstra/rest-assured-net#3]
Hi Bas,

The idea from this library looks a bit like this one:
https://github.com/WireMock-Net/WireMock.Net/wiki/FluentAssertions

(However the functionality from WireMock.Net.FluentAssertions is not yet 100% the same are your project...)

**Comment by basdijkstra** [comment]
You think so?

I’d say your FluentAssertions library is meant to check that certain calls were made to a WireMock instance when tests are run (a feature any good mocking library should provide), while this one is an attempt to make API calls and verify responses easier.

Your library acts on the provider side, mine helps at the consumer end of an API.

Or am I missing something here?

**Comment by StefH** [comment]
Let me think on that... ;-)

**Comment by basdijkstra** [comment]
Closing this for now, feel free to reopen it when you have anything to add, @StefH.
