### ISSUE TITLE
Add capability to log request details

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#33]
Can we log both requests and response for the log function ?

**Comment by basdijkstra** [comment]
Well, not yet, but that’s something that I could implement (logging requests). Consider it done! Thank you for the suggestion.

**Comment by basdijkstra** [comment]
Added in https://github.com/basdijkstra/rest-assured-net/commit/ab5ebf67b3501f99e063963cc4529970c7447843

@bheemreddy181, your feedback please? It works exactly the same as for response details, but there's an extra option to just print the endpoint.

**Comment by bheemreddy181** [comment]
do we need to add multiple log.all one for request and one for response ? @basdijkstra

**Comment by basdijkstra** [comment]
Yes.

**Comment by bheemreddy181** [comment]
Sounds good to me.
