### ISSUE TITLE
[Feature-Request] PACT Support for writing Contract Tests 

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#39]
Similar to Java RestAssured , Can we have pact DSL support? 

Example : https://hmh.engineering/how-to-write-and-validate-pact-contracts-using-junit5-and-restassured-72b578e7dd65

**Comment by basdijkstra** [comment]
Hey @bheemreddy181, can you tell me what would need to be added to RestAssured.Net to make this possible? There's nothing in that article that isn't supported already.

This example from the Pact team: https://github.com/pactflow/example-bi-directional-provider-restassured/blob/master/src/test/java/com/example/springboot/ProductsAPITest.java shows some use of a validation filter in REST Assured, so maybe that's something I can look into, but that, too, is more of a different way of validating a response than anything specific to contract testing.

That example is an example of bidirectional testing, and the provider-side contract is still going to be the OpenAPI spec (which has nothing to do with REST Assured), they just check that their responses are spec compliant before they publish the contract.

**Comment by bheemreddy181** [comment]
Agree with you, current implementation should support most of that. It would be great if you can layout an example in the documentation. Validation filter is for sure is something good to have, but that doesn't really block doing consumer driven contract tests.
