### ISSUE TITLE
Missing method for adding cookies

### ISSUE THREAD

**Issue by Constante-ou-Mort** [basdijkstra/rest-assured-net#4]
The original rest assured allows us to add a cookie after calling a given method.I think it is necessary to have the same here 🙂

**Comment by basdijkstra** [comment]
@Constante-ou-Mort absolutely. Thank you for the suggestion.

**Comment by basdijkstra** [comment]
Hey @Constante-ou-Mort, how does this look?

https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#cookies

https://github.com/basdijkstra/rest-assured-net/blob/db27f1f7fd96cc0b21f39ffc768260638f809bbb/RestAssured.Net.Tests/CookieTests.cs#L37

If that's what you're looking for, I'll include it in the next release. That'll probably be a beta, looking to add 1-2 more things in there. Hope to get that done by next week.

**Comment by basdijkstra** [comment]
The ability to add a cookie to a request, as described above, has been released with version [0.4.0](https://www.nuget.org/packages/RestAssured.Net/0.4.0).

Without any further feedback, I'm closing this issue a week from today.

**Comment by Constante-ou-Mort** [comment]
Hi, I think it's a good one, but my assumption that people will need another overloads like Cookie(System.Net.Cookie cookie){} and Cookie(System.Net.CookieCollection cookieCollection or IEnumerable<Cookie> cookies){}

**Comment by basdijkstra** [comment]
> Hi, I think it's a good one, but my assumption that people will need another overloads like Cookie(System.Net.Cookie cookie){} and Cookie(System.Net.CookieCollection cookieCollection or IEnumerable cookies){}

That makes sense :) Let me add those in a next version as well. Shouldn’t be too difficult. Thanks!

**Comment by basdijkstra** [comment]
Well, that was a little more work than I expected but it looks like it works, now. See [the tests for cookies] for examples. Is this what you were looking for? To be released in 0.4.1 in a moment.

**Comment by Constante-ou-Mort** [comment]
Yes it is) thank you very much, GJ)

**Comment by basdijkstra** [comment]
Awesome, thank you once again for the feedback and for bringing this up in the first place.

Closing this, if you ever feel there’s something else missing feel free to reopen or create a new one!
