### ISSUE TITLE
Allow 'global' disabling of SSL validation

### ISSUE THREAD

**Issue by mennopot** [basdijkstra/rest-assured-net#40]
We used your example from your blog: DeserializeIntoCSharpObject with nuget package Restassured.net 1.0.0 
There this test succeded. 
But now with version 2.0.0 it fails when using HTTPS in the get call.
With HTTP in the get call it works fine. So it looks like it does not support secure connections anymore?

We already tried to add the .Log().Body().
With a http get call, the actual body is logged.
With a httpS get call this log of the body stays empty.

**Comment by basdijkstra** [comment]
Hey Menno, have you tried disabling the SSL checks as seen in this example?

https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#disabling-ssl-checks

It completely disables the SSL validation on the HTTP client used.

If that still doesn’t work, or if you were expecting some other kind of behaviour, could you please add an example I can use to reproduce the issue?

**Comment by mennopot** [comment]
Hey Bas,

 

Thanks for the quick clarification.

This indeed works.

Though it feels strange that you need to add this to every test where you use an https request.

Is there an easier way and/or more global way?

 

Thanks.

 

Menno

 

 

Van: Bas Dijkstra ***@***.***> 
Verzonden: donderdag 24 november 2022 20:40
Aan: basdijkstra/rest-assured-net ***@***.***>
CC: mennopot ***@***.***>; Author ***@***.***>
Onderwerp: Re: [basdijkstra/rest-assured-net] https call not working in restasssured.net 2.0.0 (in visual studio) (Issue #40)

 

Hey Menno, have you tried disabling the SSL checks as seen in this example?

https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#disabling-ssl-checks

It completely disables the SSL validation on the HTTP client used.

If that still doesn’t work, or if you were expecting some other kind of behaviour, could you please add an example I can use to reproduce the issue?

**Comment by basdijkstra** [comment]
One way to configure it in a single place is by adding it to a RequestSpecification, but then you’d still need to add that RequestSpecification to each request.

Would setting it statically, just like the Java REST Assured allows, be a useful addition? In that way you’d only have to call the method once.

https://github.com/rest-assured/rest-assured/wiki/Usage#ssl

**Comment by mennopot** [comment]
Thanks, that clarifies it.

**Comment by basdijkstra** [comment]
Thanks @mennopot but I'd like to keep this one open as I think it might be a useful feature to have in the future.

**Comment by basdijkstra** [comment]
Implemented in https://github.com/basdijkstra/rest-assured-net/commit/d1a8f2144bf0e381ba758112aec53eee99e63088.
