### ISSUE TITLE
Encoded RequestURI when using QueryParam and RequestSpecBuilder

### ISSUE THREAD

**Issue by MuresanCristianRichard** [basdijkstra/rest-assured-net#47]
Hi Bas,

I noticed an issue when I try to construct the RequestURI using RequestSpecBuilder and QueryParam.
Given the following example:
```csharp
        requestSpecification = new RequestSpecBuilder()
            .WithScheme("https")
            .WithHostName("somehost.net")
            .WithBasePath("api")
            .WithOAuth2(token)
            .WithRelaxedHttpsValidation()
            .Build();
```
```csharp
   [Test]
    public void SingleQueryParameterCanBeSpecified()
    {
       Given()
        .Spec(requestSpecification)
        .QueryParam("name", "john")
        .When()
        .Get("/check-something")
        .Then()
        .StatusCode(200);
        .Extract()
        .Response();
    }
```

The result is a 404 and by debugging we got:
{Method: GET, RequestUri: 'https://somehost.net/api/check-something%3Fname=john'
->encoded

By changing the test method to this:
```csharp
    [Test]
    public void SingleQueryParameterCanBeSpecified()
    {
       Given()
        .Spec(requestSpecification)
        .QueryParam("name", "john")
        .When()
        .Get("https://somehost.net/api/check-something")
        .Then()
        .StatusCode(200);
        .Extract()
        .Response();
    }
```

that means we send the whole path for RequestURI we got the following result:
statusCode 200 and
Method: GET, RequestUri: 'https://somehost.net/api/check-something?name=john'

The encoding value from "?" to "%3F" makes the request to fail.
There is a method in Java RestAssured called:
`.urlEncodingEnabled(false)`

example:
`RequestSpecification mySpec = new RequestSpecBuilder().setUrlEncodingEnabled(false)`

Is there a way to fix this in my code or is this a Defect in library that can be released soon? 
Thanks!

**Comment by MuresanCristianRichard** [comment]
Thanks for considering this defect. 

Have a great day,
Cristian.

**Comment by basdijkstra** [comment]
I can reproduce the issue and I've located the part of the code where the problem occurs. Shouldn't take me too long to fix this.

**Comment by MuresanCristianRichard** [comment]
Sounds amazing. Thanks again!

**Comment by basdijkstra** [comment]
I think I fixed this just now. Could you please have a look at this commit?

https://github.com/basdijkstra/rest-assured-net/commit/584208bbd7da41ed426bea10d4a02acdcefeea22

And specifically whether this test represents your situation correctly: https://github.com/basdijkstra/rest-assured-net/blob/584208bbd7da41ed426bea10d4a02acdcefeea22/RestAssured.Net.Tests/QueryParameterTests.cs#L153

If so, I'll release a new version ASAP.

**Comment by MuresanCristianRichard** [comment]
Hi @basdijkstra . 
This test that you linked express exactly my situation. Looks good to me!

Have a great day!

**Comment by MuresanCristianRichard** [comment]
Looks good in our tests too. We implemented a short workaround but I just delete it and It works properly now. 
Thanks again for your quick fix. It helps a lot!

Have a great day!
