### ISSUE TITLE
Uploading a file via multipart/form-data

### ISSUE THREAD

**Issue by RipaBogdan** [basdijkstra/rest-assured-net#53]
Basically, I’m trying to “attach” and send a file, in this case a .pdf, in multipart/form-data, in order to do a POST. 

Unfortunately I don’t see anything regarding this in the documentation.

Only similar feature that I can find is using .FormData(), however it seems that this accepts only a <string, string> type of Dictionary. (I’ve tried converting the file .ToBase64String, but I still see a 500 StatusCode)
I’ve seen in the Java version of Rest Assured that .multiPart() is available, where you can send the file along with the file type. 

Can something similar be implemented? 
Thank you.

**Comment by basdijkstra** [comment]
Here's the relevant documentation from REST Assured: https://github.com/rest-assured/rest-assured/wiki/Usage#multi-part-form-data

**Comment by basdijkstra** [comment]
Thank you, @RipaBogdan, I'll try and get to work on this ASAP.

**Comment by basdijkstra** [comment]
Hey @RipaBogdan, just a quick check, here's the resulting request of the first, very simple file upload mechanism I've implemented, tested with a plain text file. Does this look good to you?

![image](https://user-images.githubusercontent.com/10740451/221228273-2f41ceae-b098-4ab5-a512-7806963bb20d.png)

If so I can clean up the code, add overloads for custom file handle specification and allow multiple files to be uploaded.

**Comment by RipaBogdan** [comment]
> Hey @RipaBogdan, just a quick check, here's the resulting request of the first, very simple file upload mechanism I've implemented, tested with a plain text file. Looks the same to me as what the Java Rest Assured produces.
> 
> Does this look good to you?
> 
> ![image](https://user-images.githubusercontent.com/10740451/221228273-2f41ceae-b098-4ab5-a512-7806963bb20d.png)
> 
> If so I can clean up the code, add overloads for custom file handle specification and allow multiple files to be uploaded.

Hi @basdijkstra, looks good from my side. Thank you!

**Comment by basdijkstra** [comment]
Thanks! I’ll build the rest of the feature on top of this then. Probably early next week.

**Comment by basdijkstra** [comment]
Hey @RipaBogdan, I've just released package version 2.3.0-beta on NuGet: https://www.nuget.org/packages/RestAssured.Net/2.3.0-beta

You can test multipart file upload there by using `Given().MultiPart(<your_file_name>)` (if the file control name is 'file') or `Given().MultiPart(<your_control_name>, <your_file_name>)` for non-standard control names.

Could you please test this and let me know if it works? See the tests for working examples.

Also please let me know if you think something is missing here. At the moment it's only possible to upload a single file, for example, and I haven't built the MultiPart spec builder that the Java REST Assured has.

I can always add that, but, you know, YAGNI :)

**Comment by RipaBogdan** [comment]
Hi @basdijkstra,

I've tested it and it works perfectly. Seems that you can add a path, not only the file name which is useful. 
I guess multiple files will be needed in the future, but as per my initial issue, I think it is resolved.

Thanks a lot!

**Comment by basdijkstra** [comment]
Thanks! I've just released this with version `2.3.0`, should be available through NuGet very soon: https://www.nuget.org/packages/RestAssured.Net/2.3.0
