### ISSUE TITLE
MultiPart overload for ContentTypeForFile

### ISSUE THREAD

**Issue by MuresanCristianRichard** [basdijkstra/rest-assured-net#58]
Hi Bas,

I am trying to upload a File using MultiPart method that has extentions .csv and I am facing an issue because the request is using default file content type as below:
![image](https://user-images.githubusercontent.com/108386717/228869128-803fc567-efe3-42f3-85ed-e30c669e69f6.png)

but the endpoint request as below:
![image](https://user-images.githubusercontent.com/108386717/228869279-fbc1b0f9-2644-49e6-9604-4076477212c7.png)

Is there a way that you can overload the MultiPart method so it accepts custom File ContentType as example: "text/csv" instead of this:
![image](https://user-images.githubusercontent.com/108386717/228869838-a92a4f75-4765-4e15-a153-ed60cf2b1bf5.png)

Also is possible to keep in mind as future improvements to upload multiple files as bulk at the same time using the same method MultiPart?

Have a great day ahead!
Thanks!
Cristian.

**Comment by basdijkstra** [comment]
Hey @MuresanCristianRichard,

the first part of your request is fairly straightforward, so I'll implement and release that tomorrow. I'll look into uploading multiple files, too, although that might take me a little longer. Or maybe not. We'll see. I'll keep you posted!

**Comment by MuresanCristianRichard** [comment]
Sounds great! 

Thanks!
Cristian

**Comment by basdijkstra** [comment]
Quick question: because the control name is also optional, and all arguments are strings, it's impossible to determine which value goes where without using named arguments when you call the `MultiPart()` method.

So, this:
```csharp
Given().MultiPart(controlName: "customControl", fileName: this.csvFileName, contentType: "text/csv")
```
Alternatives are
* Creating a method with a different name (I don't like this)
* See if there's another data type that I can use to make it easier to use the overload, but this _might_ break the library API, which I also don't like

Thoughts / ideas are welcome, I'll have a good think about this tonight / tomorrow, too.

**Comment by basdijkstra** [comment]
@MuresanCristianRichard, I'm thinking of deprecating the existing `MultiPart()` methods (so you can still use them) and providing a new one with three arguments:
* `fileName` of type [FileInfo](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo?view=net-7.0) - mandatory
* `controlName` of type string - optional, defaults to `file`
* `contentType` of type [MediaTypeHeaderValue](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.headers.mediatypeheadervalue?view=net-7.0) - optional, when left empty it will be determined automatically as we do right now

Your thoughts?

**Comment by MuresanCristianRichard** [comment]
Hi @basdijkstra,

Deprecating MultiPart() method and providing a new one with three arguments sounds good to me.
Also having default values as MultiPart() is working right now is nice because there will be edge cases when we need to override these arguments, so mostly we will stick to what exists.

Thanks,
Have a great day,
Cristian

**Comment by basdijkstra** [comment]
Thanks for the quick response. I'll get to work on that later today! Will let you know once I've published a test/preview version.

**Comment by basdijkstra** [comment]
@MuresanCristianRichard, version `2.5.0-beta` is now available on NuGet: https://www.nuget.org/packages/RestAssured.Net/2.5.0-beta

Could you please have a look at the new `MultiPart()` method overloads? Signature looks like this:

```csharp
public ExecutableRequest MultiPart(FileInfo fileName, string controlName = "file", MediaTypeHeaderValue? contentType = null)
```

As you can see, `controlName` defaults to `file` as it used to do, `contentType` defaults to `null`, in which case it will be automatically determined as before. If specified, the specified value will be used.

Looking forward to your feedback.

**Comment by MuresanCristianRichard** [comment]
Hi @basdijkstra 

Sorry for late answer.
Looks good to me. I`ve tested and it works. I successfully imported a CSV file using that method. 

Thanks,
Have a great day!
Cristian

**Comment by basdijkstra** [comment]
No worries, thank you for letting me know @MuresanCristianRichard. I'll have a quick look to see if I can also add uploading multiple files (or rather, if calling `MultiPart()` multiple times adds separate files properly) and then I'll create a new proper release later this week.

**Comment by basdijkstra** [comment]
I did a very small but important fix in the way multipart form data is added, which now also makes it possible to upload multiple files in a single API call. What you need to do, like in the original REST Assured, is adding multiple calls to `MultiPart()`.

See this commit and especially the test for an example: https://github.com/basdijkstra/rest-assured-net/commit/c67c06dc25affcaac4a6328ce73716c9f68efb36

@MuresanCristianRichard hope this helps. I'll close this issue when 2.5.0 is released.

**Comment by MuresanCristianRichard** [comment]
Hi @basdijkstra 

Sure uploading multiple files using multiple MultiPart() calls will help. Thanks a lot!
Thanks for enhancement too!

Cristian
