### ISSUE TITLE
Improve support for HTML response bodies

### ISSUE THREAD

**Issue by workmichsem** [basdijkstra/rest-assured-net#70]
Hello
Please tell me how to get response body in C# when Content-Type is 'text/html'?
I tried to use
```
.Extract().Body("").ToString()
or
.Extract().Response().ToString();
```
but it doesn't work
My response semse like this
```
HTTP 403 (Forbidden)
Content-Type: text/html
Content-Length: 1233
Cache-Control: private
Server: Microsoft
X-AspNet-Version: 4.0.30000
X-Powered-By: ASP.NET
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=300
Date: Thu, 04 May 2023 04:19:52 GMT

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>403 - Forbidden: Access is denied.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>403 - Forbidden: Access is denied.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

**Comment by basdijkstra** [comment]
So, there's no 'proper' native support for dealing with HTML response bodies at the moment, but there's a straightforward workaround.

I've included that as an example here: https://github.com/basdijkstra/rest-assured-net/blob/c3ed36dd62eef25cdd7630d9fe2c3ac1b963df06/RestAssured.Net.Tests/ResponseBodyHtmlVerificationTests.cs#L67

All HTML examples can be found in https://github.com/basdijkstra/rest-assured-net/blob/main/RestAssured.Net.Tests/ResponseBodyHtmlVerificationTests.cs

@workmichsem, please let me know if that's acceptable as a workaround for now. I'd like to keep this issue open even if it is, as a reminder that I should work on improving HTML support.

**Comment by workmichsem** [comment]
I wish it looked shorter.
However, the current solution completely solves my problem.

@basdijkstra 
Thank you very much for your prompt response as always.

**Comment by basdijkstra** [comment]
You're welcome, @workmichsem. I can't really make it shorter at the moment as I'm working with the .NET built-in `HttpResponseMessage` type.

But, as I said, I'll update this issue and see if and how I can improve support for HTML responses.

**Comment by basdijkstra** [comment]
Note to self:

* Write a mock that returns an HTML response body
* Enable RestAssured.Net to verify HTML response body elements
* Enable RestAssured.Net to extract HTML response body elements

**Comment by basdijkstra** [comment]
@workmichsem I've just committed https://github.com/basdijkstra/rest-assured-net/commit/fbf0b5fc1c7b05b1fd8740f028ad6401c89f8948, would you be so kind as to have a look at https://github.com/basdijkstra/rest-assured-net/blob/main/RestAssured.Net.Tests/ResponseBodyHtmlVerificationTests.cs and see if there's anything you're missing?

I've added [HtmlAgilityPack](https://html-agility-pack.net/) as a dependency, which makes working with HTML content very, very similar to working with XML, as you can tell from the examples. XPath is XPath, no matter if you're working with XML or HTML :)

I still need to add support for extracting HTML response values, but with this commit users can verify them already.

**Comment by workmichsem** [comment]
@basdijkstra hello!
Looks great!
Thank you for implementing this feature so quickly.

**Comment by basdijkstra** [comment]
HTML element extraction added in https://github.com/basdijkstra/rest-assured-net/commit/26d6565f798f3601216e434db6af940d82c779f7. Closing this issue now, I'll release these capabilities in version 2.6.0 later this week.
