### ISSUE TITLE
Debug Assemblies in NuGet packages on NuGet.org

### ISSUE THREAD

**Issue by SabotageAndi** [basdijkstra/rest-assured-net#80]
The assemblies in the NuGet packages on NuGet.org are Debug assemblies.

![image](https://github.com/basdijkstra/rest-assured-net/assets/859801/8f54b40a-1d7c-4247-b513-275e358fd71d)

Is this on purpose?

**Comment by basdijkstra** [comment]
No, but you’re right that Release would probably be a better value here.

**Comment by basdijkstra** [comment]
This is a straightforward one in the end, I just need to make sure to create a Release build and publish that, using

`dotnet build --configuration Release`

Will do that from version 2.9.0 onwards, which should be released in a week or so.
