### ISSUE TITLE
Content Type: application/json and Body as String format not working without additional formatting

### ISSUE THREAD

**Issue by MuresanCristianRichard** [basdijkstra/rest-assured-net#86]
Hi Bas,
Hope you are well!

I am facing an issue for an endpoint that accepts:
Content Type: application/json
And input as a String.
(directly a String, JSON without a key)

In one scenario, the input in string format could be an XML. 
Given this, when I am sending the request, it fails because RestAssured is sending the request without Quotation marks ("string" will be provided to endpoint only like this: string). <br />
To be more explicit:
Input should look like:
`"<?xml version=\"1.0\" .........> "`
When I send the request to the endpoint will be provided only: 
 `<?xml version=\"1.0\" .........>`

If I append to the String like in following example: 
`var newString = "\"" + xmlString + "\"";`
This will fail too because this:
`\"<?xml version=\"1.0\" .........> \"` to be valid requires it to look like:
`\"<?xml version=\\\"1.0\\\" .........> \"` -> this is working but...
That requires additional formatting that is not bulletproof and it may cause the test to be flaky.

Hope I was clearly enough so you can understand the problem. 
Do you think that there is a way that you can improve so it will work for our case without that additional formatting?
We just need RestAssured to send the string (that is not an object, just a json as string) with Quotation marks in payload.

Have a great day ahead! <br />
Thanks! 
Cristian.

**Comment by basdijkstra** [comment]
So, when I do this test:

```csharp
[Test]
public void PlaintextRequestBodyWithLeadingAndTrailingQuotesCanBeSupplied()
{
    Given()
        .ContentType("application/json")
        .Body("\"Banana\"")
        .When()
        .Post("http://localhost:9876/plaintext-request-body-with-quotes")
        .Then()
        .StatusCode(201);
}
```

the request looks like this, with double quotes preserved:

![image](https://github.com/basdijkstra/rest-assured-net/assets/10740451/d0f84570-3e6c-4402-b136-59871a472ff5)

Am I missing something here?

**Comment by MuresanCristianRichard** [comment]
Hi Bas,

The problem is that we are talking about an XML file which has more quotes in it.
Maybe using your example we can reproduce.

What if we use that example:
```
[Test]
public void PlaintextRequestBodyWithLeadingAndTrailingQuotesCanBeSupplied()
{
var stringExample = "<?xml version=\"1.0\"?>";
var addQuotes = "\"" + stringExample + "\"";
    Given()
        .ContentType("application/json")
        .Body(addQuotes)
        .When()
        .Post("http://localhost:9876/plaintext-request-body-with-quotes")
        .Then()
        .StatusCode(201);
}
```

**Comment by basdijkstra** [comment]
Here's what that looks like on my machine right now:

```csharp
[Test]
public void PlaintextRequestBodyWithLeadingAndTrailingQuotesCanBeSupplied()
{
    Given()
        .ContentType("application/json")
        .Body("\"Banana\"")
        .When()
        .Post("http://localhost:9876/plaintext-request-body-with-quotes")
        .Then()
        .StatusCode(201);
}
```

and the request:

![image](https://github.com/basdijkstra/rest-assured-net/assets/10740451/ba361af1-fd5b-4fcc-a0a4-d65a15928aec)

**Comment by MuresanCristianRichard** [comment]
Yea, I perfectly understand that but my concern was if lets say someone will send input in XML like that:
"Connection\ready" for some reason, the test will fail because It will replace \r with empty.String.

Anyway I will go ahead and talk to our dev team to see if they can help somehow and improve our endpoint.

A very specific logic only for our case is not a solution in my opinion. It s better to workaround on our side than doing specific cases in a library like RestAssured.

Thanks a lot Bas,
Have a great day,
Cristian

**Comment by basdijkstra** [comment]
Thanks, @MuresanCristianRichard. Closing this now.
