### ISSUE TITLE
Introduce Faker.Net for mocks and Tests package

### ISSUE THREAD

**Issue by guneshpatil** [basdijkstra/rest-assured-net#87]
- use Faker library to add data variations in the tests and mocks being set
- also, refactor multiple usage of WireMock server url with constant

**Comment by basdijkstra** [comment]
Looks good to me, @guneshpatil, good luck! Let me know if you need any help. Looking forward to the pull request.

**Comment by basdijkstra** [comment]
Merged, so closing this issue now.
