### ISSUE TITLE
[Question] Any recommendations on Chained API requests

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#9]
Hey - do you any recommendations on chained API request like 

If API-B is dependent on API-A (test data created here is input for API-B).

Do we do like below.

1. Given setup for request A and do all validations on that request and extract the response.
2. Use the Above response to create a JSON for API-B.

    Well, we do this in real world, but curious on how the test should be written here. There could be cases where a data for One API is created from multiple other APIs as well.

**Comment by basdijkstra** [comment]
Yes, that's exactly why I added the `Extract()` methods, to be able to extract specific response header or body values (or even the entire response message) so they can be reused in later requests.

A common example is getting an authentication token:

```csharp
[Test]
public void GetToken()
{
    string token = (string)Given()
    .When()
    .Get("http://localhost:9876/token")
    .Then()
    .StatusCode(200)
    .Extract().Body("$.token");

    Given()
    .OAuth2(token)
    .When()
    .Get("https://localhost:9876/some-secure-endpoint")
    .Then()
    .StatusCode(200);
}

Does that answer your question?

**Comment by bheemreddy181** [comment]
That makes sense.
