### ISSUE TITLE
Feature: Response size

### ISSUE THREAD

**Issue by christiaanwvermaak** [basdijkstra/rest-assured-net#92]
Please provide a mechanism to retrieve the size of the response. This can be split between the response headers and response body. It will enable quick test to see if the response is the same when comparing the sizes of the response bodies.

**Comment by basdijkstra** [comment]
Hey @christiaanwvermaak, as discussed, these features are added in https://github.com/basdijkstra/rest-assured-net/commit/096bb6f1cdecf541dc44f48d70105ad2353e3fdd.

https://github.com/basdijkstra/rest-assured-net/blob/main/RestAssured.Net.Tests/ResponseBodyLengthVerificationTests.cs contains examples on:

* How to verify the response body length using an NHamcrest matcher
* How to extract the entire response body as a `string` and verify its length

Please note that the response body length verification is based on the _actual_ response body, not on the value of the `Content-Length` header.

Please test this using version `3.0.0-beta.3` and close this issue when you think it has been properly addressed.

**Comment by basdijkstra** [comment]
Closing this as discussed with @christiaanwvermaak.
