### ISSUE TITLE
Please tag releases in the source code

### ISSUE THREAD

**Issue by aaschmid** [basdijkstra/rest-assured-net#95]
We would like to use this great library in the open source project [catenax-ng/tx-portal-backend](https://github.com/catenax-ng/tx-portal-backend) which requires all used libraries to have reproduceable releases. Git tags and release versions in GitHub would be sufficient. 

Starting from 2.8.1, it is not necessary to also tag the previous versions, just 2.8.1 and future ones would be OK.

**Comment by basdijkstra** [comment]
Hi Andreas,

you caught me in the middle of releasing version 3.0.0. The current state of `main` now reflects what will be released in 3.0.0, I'm about to push that to NuGet.

Do you still want me to tag for version 2.8.1, too?

Thank you for including this library in your project :)

**Comment by basdijkstra** [comment]
I've gone ahead and tagged versions 2.8.1 and 3.0.0 in the code: https://github.com/basdijkstra/rest-assured-net/tags

Please let me know if that is sufficient for you. I'll make sure to do this for any future release from here on.

**Comment by aaschmid** [comment]
It is sufficient to use tags, thanks!

**Comment by basdijkstra** [comment]
Perfect, thank you for letting me know!
