### ISSUE TITLE
Possibility to replace `Newtonsoft.Json.Schema` with something having a more friendly license

### ISSUE THREAD

**Issue by aaschmid** [basdijkstra/rest-assured-net#96]
Unfortunately, we encountered another issue with this library for using it for our open source project [catenax-ng/tx-portal-backend](https://github.com/catenax-ng/tx-portal-backend). Problem is that your `Newtonsoft.Json.Schema` dependency is published under "GNU Affero General Public License" which is incompatible with our project and the standards of Eclipse foundation.

As far as I understand, this dependency is only used in `VerifiableResponse.cs` (see [code)](https://github.com/basdijkstra/rest-assured-net/blob/6c5711dd7d59cd8d9c7e6dcf3ce89f9c3610a1ed/RestAssured.Net/Response/VerifiableResponse.cs)) and also not further referenced in the production / shipped code.

Do you see any possibilities to get either replace it by an alternative e.g. https://github.com/gregsdennis/json-everything (published under MIT) or release and maintain a version without it?

CC @evegufy

**Comment by basdijkstra** [comment]
Hey @aaschmid, let me think about this for a bit. I don’t really feel like maintaining a separate version without that dependency but I’m happy to see if there’s an alternative for the JSON schema validation.

I’ve not really looked at the license but I see how this can be problematic, so replacing it is worth investigating.

I’ll get back to you soon.

**Comment by basdijkstra** [comment]
Hey @aaschmid and @evegufy, two questions:

* Would [NJsonSchema](https://github.com/RicoSuter/NJsonSchema) be a viable alternative? It seems easy enough to use
* For approval, would you require me to entirely remove the dependency to `Newtonsoft.Json.Schema`, or would deprecating the methods that use them and providing alternatives using `NJsonSchema` be good enough for now?

Reason for question 2 is the fact I just released a new major version yesterday and given that this would be a breaking change (even if only of a single method that I suspect isn't really used all that often anyway) it would require me to bump the major version once again.

Cheers!

**Comment by evegufy** [comment]
Hi @basdijkstra thank you so  much for considering this change!

I checked [NJsonSchema](https://github.com/RicoSuter/NJsonSchema) 10.9.0 and it seems viable, the License is alright and also the source is tagged.

`Newtonsoft.Json.Schema` would needed to be gone when doing a `dotnet list package`, so deprecating the methods unfortunately wouldn't be quite sufficient. Sorry for the inconvenience of a possible major version bump!

**Comment by basdijkstra** [comment]
Hi @evegufy, no worries, that makes sense.

I've gone ahead and replaced `Newtonsoft.Json.Schema` with `NJsonSchema` now, here's the updated output:

```console
Project 'RestAssured.Net' has the following package references
   [net6.0]: 
   Top-level Package                        Requested   Resolved
   > HtmlAgilityPack                        1.11.49     1.11.49 
   > Microsoft.AspNetCore.StaticFiles       2.2.0       2.2.0   
   > Microsoft.AspNetCore.WebUtilities      2.2.0       2.2.0   
   > Newtonsoft.Json                        13.0.3      13.0.3  
   > NHamcrest                              3.2.0       3.2.0   
   > NJsonSchema                            10.9.0      10.9.0  
   > Stubble.Core                           1.10.8      1.10.8  
   > StyleCop.Analyzers                     1.1.118     1.1.118 
   > System.Text.Encodings.Web              6.0.0       6.0.0   

   [net7.0]: 
   Top-level Package                        Requested   Resolved
   > HtmlAgilityPack                        1.11.49     1.11.49 
   > Microsoft.AspNetCore.StaticFiles       2.2.0       2.2.0   
   > Microsoft.AspNetCore.WebUtilities      2.2.0       2.2.0   
   > Newtonsoft.Json                        13.0.3      13.0.3  
   > NHamcrest                              3.2.0       3.2.0   
   > NJsonSchema                            10.9.0      10.9.0  
   > Stubble.Core                           1.10.8      1.10.8  
   > StyleCop.Analyzers                     1.1.118     1.1.118 
   > System.Text.Encodings.Web              6.0.0       6.0.0
```

If you think this is OK, I'll publish RestAssured.Net `4.0.0-alpha.1` for you to try out if that helps.

I appreciate you and @aaschmid pointing out that `Newtonsoft.Json.Schema` has a (semi-)commercial license, I'm happy to get rid of it.

**Comment by evegufy** [comment]
Hi @basdijkstra I checked and that output looks really good! 
It'd be awesome if you could publish the with 4.0.0-beta.1.
Thanks again!

**Comment by basdijkstra** [comment]
@evegufy here you go: https://www.nuget.org/packages/RestAssured.Net/4.0.0-beta.1

Please let me know if everything is in order with this latest release, I'd love to see RestAssured.Net used in your project.

A 'proper' version 4.0.0 will follow soon, but do let me know when you need it earlier than I provide it. There are some other features that I think I want to put in 4.0.0.

**Comment by basdijkstra** [comment]
Hi @evegufy, @aaschmid,

I see this new build passed your checks: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9294

As I’m going on holiday for three weeks a week from now, is there anything you need from me this coming week to keep things moving?

I’ll keep track of any open issues but obviously won’t do a lot of dev work until I get back to work August 8 ;)

**Comment by evegufy** [comment]
Hi @basdijkstra

yes, the IP issue was approved 🤩

Sure, go ahead closing the issue (I can't as I didn't open it) there's no reason to keep the open.

Thanks again for your help and have a great holiday!

Cheers
Evelyn

**Comment by basdijkstra** [comment]
Closing this as discussed.
